### ISSUE TITLE
.NET Framework compatibility

### ISSUE THREAD

**Issue by igor-gorjanc** [OlegRa/System.DateTimeOnly#5] opened 2022-06-14 15:50 UTC
Package fails to install e.g. on a .NET Framework 4.8 based project. 
According to Nuget it works with some lower and also with some higher .NET versions.
Please add missing .NET framework versions to the TargetFrameworks section.

**Comment by OlegRa** [comment] 2022-06-15 10:49
I'm unable to reproduce it on my side. In a newly created .NET Framework 4.8 console application I execute the next command for adding the NuGet package:

```
Install-Package Portable.System.DateTimeOnly -Version 6.0.1
```

The output states that all required dependent packages and the target package itself are installed correctly:

```
Attempting to gather dependency information for package 'Portable.System.DateTimeOnly.6.0.1' with respect to project 'DateTimeOnlyTest', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 6.75 sec
Attempting to resolve dependencies for package 'Portable.System.DateTimeOnly.6.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Portable.System.DateTimeOnly.6.0.1'
Resolved actions to install package 'Portable.System.DateTimeOnly.6.0.1'
Retrieving package 'Portable.System.DateTimeOnly 6.0.1' from 'nuget.org'.
Retrieving package 'System.Buffers 4.5.1' from 'nuget.org'.
Retrieving package 'System.Memory 4.5.4' from 'nuget.org'.
Retrieving package 'System.Numerics.Vectors 4.5.0' from 'nuget.org'.
Retrieving package 'System.Runtime.CompilerServices.Unsafe 4.5.3' from 'nuget.org'.
Adding package 'System.Buffers.4.5.1' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Buffers.4.5.1' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Buffers.4.5.1' to 'packages.config'
Successfully installed 'System.Buffers 4.5.1' to DateTimeOnlyTest
Adding package 'System.Numerics.Vectors.4.5.0' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Numerics.Vectors.4.5.0' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Numerics.Vectors.4.5.0' to 'packages.config'
Successfully installed 'System.Numerics.Vectors 4.5.0' to DateTimeOnlyTest
Adding package 'System.Runtime.CompilerServices.Unsafe.4.5.3' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Runtime.CompilerServices.Unsafe.4.5.3' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Runtime.CompilerServices.Unsafe.4.5.3' to 'packages.config'
Successfully installed 'System.Runtime.CompilerServices.Unsafe 4.5.3' to DateTimeOnlyTest
Adding package 'System.Memory.4.5.4' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Memory.4.5.4' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'System.Memory.4.5.4' to 'packages.config'
Successfully installed 'System.Memory 4.5.4' to DateTimeOnlyTest
Adding package 'Portable.System.DateTimeOnly.6.0.1' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'Portable.System.DateTimeOnly.6.0.1' to folder 'C:\Projects\DateTimeOnlyTest\packages'
Added package 'Portable.System.DateTimeOnly.6.0.1' to 'packages.config'
Successfully installed 'Portable.System.DateTimeOnly 6.0.1' to DateTimeOnlyTest
Executing nuget actions took 3.49 sec
Time Elapsed: 00:00:10.5703879
```

I've made a short test that demonstrates that the `DateOnly` type is work as expected and also demonstrates that the runtime framework is 4.8 as expected:

```cs
using System;
using System.Runtime.InteropServices;

namespace DateTimeOnlyTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            Console.WriteLine(DateOnly.FromDateTime(DateTime.Today));
        }
    }
}
```

The screenshot of this application running on my development box:

![image](https://user-images.githubusercontent.com/4800940/173808027-e38846c9-fa01-4b18-88d2-e30e8ca1c7d3.png)

If I check the real reference in the `.csproj` file it correctly points to the 4.6.1 version of the `Portable.System.DateTimeOnly` version of the assembly:

```
<Reference Include="Portable.System.DateTimeOnly, Version=6.0.1.2, Culture=neutral, PublicKeyToken=16fb7a27ac3b9689, processorArchitecture=MSIL">
  <HintPath>packages\Portable.System.DateTimeOnly.6.0.1\lib\net461\Portable.System.DateTimeOnly.dll</HintPath>
</Reference>
```

It's not a good idea to add separate binaries for each supported framework into the NuGet package if these binaries are identical. You just make the `.nupkg` file bigger without any other benefits. The NuGet client uses a simple backward-compatibility rule and in the case of any .NET Framework target with a version equal to or greater than 4.6.1 will use the proper assembly version specific to .NET Framework 4.6.1, not the .NET Standard or .NET 5 version.

@igor-gorjanc Please, provide the output of the `Install-Package` command with exact error messages and I'll try to help you. Most probably the real root cause is some 2-nd or 3-rd level dependency conflict, not related to the package itself.

**Comment by OlegRa** [comment] 2022-06-28 07:14
@igor-gorjanc I'll close this issue for now. If you still have a problem with the NuGet package, please, re-open this issue and provide all the requested information.

**Closed as completed by OlegRa** 2022-06-28 07:14 UTC
Labels: bug, question

**Comment by OlegRa** [comment] 2023-06-09 06:01
@all-contributors please add @igor-gorjanc for bug.
